### ISSUE TITLE
v-model 默认值不是双向绑定？

### ISSUE THREAD

**Issue by Nutlee** [ElementUI/region-picker#3]
您好，拿您的代码试了下，v-model 似乎不是双向绑定的..  看了下源码，单选模式 single.vue 里提供       了select({}) 可以置空，但是该方法并没有往顶层暴露...    😌 有点尴尬.. 

有遇到多选清空表单的业务场景，貌似只能通过 v-if 重绘或者去清空掉dom了，心塞.. 

才疏学浅，或许我姿势不对？

谢谢

**Comment by liril-net** [comment]
是双向绑定的
